-- ============================================================
--  Member Vaults – Database Schema
--  Import via phpMyAdmin or: mysql -u root < membervaults.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS membervaults CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE membervaults;

-- ------------------------------------------------------------
-- Plans
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS plans (
    id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name          VARCHAR(50)    NOT NULL,
    tier          TINYINT        NOT NULL COMMENT '1=Free 2=Silver 3=Gold 4=Premium',
    price         DECIMAL(8,2)   NOT NULL DEFAULT 0.00,
    duration_days INT            NOT NULL DEFAULT 30 COMMENT '0 = lifetime/free',
    badge_color   VARCHAR(30)    NOT NULL DEFAULT '#00ffff',
    features      JSON           NOT NULL,
    created_at    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Users
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(60)    NOT NULL UNIQUE,
    email         VARCHAR(120)   NOT NULL UNIQUE,
    password_hash VARCHAR(255)   NOT NULL,
    role          ENUM('user','admin') NOT NULL DEFAULT 'user',
    created_at    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Subscriptions
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subscriptions (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id     INT UNSIGNED   NOT NULL,
    plan_id     INT UNSIGNED   NOT NULL,
    start_date  DATE           NOT NULL,
    expiry_date DATE           NULL COMMENT 'NULL = never expires (Free permanent)',
    status      ENUM('active','expired','cancelled') NOT NULL DEFAULT 'active',
    created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)  ON DELETE CASCADE,
    FOREIGN KEY (plan_id) REFERENCES plans(id)  ON DELETE RESTRICT
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Audit Log
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id    INT UNSIGNED NULL,
    action     VARCHAR(100) NOT NULL,
    detail     TEXT         NULL,
    ip_address VARCHAR(45)  NULL,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ============================================================
-- Seed Data
-- ============================================================

INSERT INTO plans (name, tier, price, duration_days, badge_color, features) VALUES
('Free',    1, 0.00,  0,  '#6b7280', JSON_ARRAY('Public articles','Basic profile','Community access')),
('Silver',  2, 9.99,  30, '#94a3b8', JSON_ARRAY('Everything in Free','Community forum','Monthly newsletter','Download resources')),
('Gold',    3, 19.99, 30, '#f59e0b', JSON_ARRAY('Everything in Silver','Premium tutorials','Priority support','Advanced analytics')),
('Premium', 4, 39.99, 30, '#a855f7', JSON_ARRAY('Everything in Gold','Exclusive vault content','1-on-1 sessions','API key access','Lifetime updates'));

-- Default admin  (password: Admin@1234)
INSERT INTO users (username, email, password_hash, role) VALUES
('admin', 'admin@membervaults.com',
 '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
 'admin');
-- NOTE: The hash above is bcrypt of 'Admin@1234' generated with password_hash().
--       Replace with a fresh hash generated by your own PHP if preferred.
